-- Table catalogue des étapes de production
CREATE TABLE public.etapes_production_catalogue (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  operation TEXT NOT NULL UNIQUE,
  taux_horaire NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.etapes_production_catalogue ENABLE ROW LEVEL SECURITY;

-- Lecture publique pour tous les utilisateurs authentifiés
CREATE POLICY "Authenticated users can view production steps catalog"
ON public.etapes_production_catalogue
FOR SELECT
USING (auth.uid() IS NOT NULL);

-- Insertion par utilisateurs authentifiés
CREATE POLICY "Authenticated users can insert production steps"
ON public.etapes_production_catalogue
FOR INSERT
WITH CHECK (auth.uid() IS NOT NULL);

-- Insérer les données du fichier Excel
INSERT INTO public.etapes_production_catalogue (operation, taux_horaire) VALUES
('Réception et contrôle des matières premières', 17.45),
('Tri et classification des granulés plastiques', 13.80),
('Séparation des matières recyclées', 21.20),
('Séchage des granulés pour éliminer l''humidité', 16.95),
('Pesage et dosage des additifs', 14.75),
('Pré-mélange des polymères', 18.60),
('Contrôle qualité des matières premières', 22.10),
('Stockage temporaire des matières premières', 13.50),
('Extrusion de profilés plastiques', 28.40),
('Injection de pièces techniques', 31.20),
('Soufflage de bouteilles ou contenants', 26.15),
('Thermoformage de films et plaques', 24.90),
('Calandrage de feuilles plastiques', 20.80),
('Pultrusion pour fibres plastiques', 23.60),
('Co-extrusion multicouche', 27.50),
('Refroidissement des pièces extrudées', 15.75),
('Démoulage des pièces injectées', 19.20),
('Contrôle dimensionnel post-injection', 22.90),
('Découpe et tronçonnage des pièces', 18.40),
('Gravure ou marquage laser', 23.75),
('Polissage et finition des surfaces', 20.10),
('Assemblage de composants plastiques', 21.50),
('Soudage par ultrasons', 26.80),
('Collage et assemblage chimique', 24.35),
('Perçage et taraudage', 17.95),
('Inspection visuelle de surface', 16.50),
('Test mécanique (traction, flexion, dureté)', 21.80),
('Test thermique et résistance à la chaleur', 23.40),
('Test chimique et compatibilité', 22.10),
('Inspection dimensionnelle et tolérances', 20.95),
('Contrôle optique (transparence, couleur)', 19.60),
('Test d''étanchéité pour contenants', 24.20),
('Conditionnement et emballage', 15.30),
('Étiquetage des produits finis', 13.95),
('Stockage dans entrepôt', 12.80),
('Préparation des commandes', 14.50),
('Expédition et logistique', 16.10),
('Gestion des retours et recyclage interne', 18.20),
('Séchage des granulés pour extrusion', 17.30),
('Test qualité des matières recyclées', 19.80),
('Préparation des moules d''injection', 21.90),
('Montage des filières d''extrusion', 22.50),
('Refroidissement des films thermoformés', 16.70),
('Découpe des plaques thermoformées', 18.25),
('Inspection visuelle des bouteilles soufflées', 19.10),
('Polissage des surfaces injectées', 20.50),
('Test de résistance mécanique sur profilés', 22.30),
('Assemblage des ensembles plastiques', 23.75),
('Étiquetage et marquage laser des pièces', 17.80),
('Stockage temporaire post-production', 14.20),
('Transport interne des produits finis', 12.95),
('Contrôle de la viscosité des polymères', 18.50),
('Préparation des additifs colorants', 16.90),
('Dosage des stabilisants thermiques', 17.75),
('Mélange homogène des granulés', 19.20),
('Test d''humidité des matières premières', 15.60),
('Chargement des granulés dans la trémie', 14.80),
('Réglage de la machine d''extrusion', 22.10),
('Réglage de la presse à injection', 23.50),
('Calibration des moules thermoformage', 20.40),
('Contrôle de la température du four', 18.75),
('Inspection dimensionnelle des pièces', 21.20),
('Test de résistance chimique', 22.90),
('Contrôle optique des pièces', 19.40),
('Contrôle du poids des pièces', 17.85),
('Refroidissement des pièces injectées', 16.90),
('Démoulage des pièces thermoformées', 18.50),
('Découpe des produits extrudés', 19.30),
('Perçage des pièces assemblées', 21.50),
('Soudage plastique par ultrasons', 26.10),
('Collage chimique des composants', 24.60),
('Gravure des étiquettes', 18.95),
('Marquage au laser des produits', 20.40),
('Polissage des surfaces thermoformées', 21.10),
('Test mécanique des profilés', 23.50),
('Test thermique des bouteilles', 22.20),
('Inspection qualité des emballages', 19.80),
('Conditionnement dans cartons', 15.40),
('Étiquetage manuel des produits', 14.70),
('Stockage des produits finis', 12.95),
('Préparation des palettes pour expédition', 16.20),
('Chargement des camions', 17.35),
('Gestion des retours et tri', 18.50),
('Contrôle qualité des matières recyclées', 19.25),
('Séchage des granulés post-recyclage', 16.80),
('Préparation des moules d''extrusion', 21.10),
('Montage des filières de calandrage', 22.00),
('Refroidissement des plaques calandrées', 16.95),
('Découpe des plaques calandrées', 18.10),
('Inspection visuelle des plaques', 19.30),
('Polissage des bords découpés', 20.50),
('Assemblage de composants thermoformés', 21.20),
('Soudure plastique par chaleur', 25.80),
('Collage par solvant', 24.10),
('Test d''étanchéité des contenants', 23.60),
('Contrôle dimensionnel final', 22.10),
('Test de résistance aux chocs', 21.75),
('Inspection optique des produits finis', 19.80),
('Étiquetage et code-barres', 17.25),
('Conditionnement en sacs', 14.90),
('Stockage en rack', 13.50),
('Transport interne au dépôt', 12.80),
('Préparation pour expédition internationale', 16.50),
('Chargement de conteneurs', 18.10),
('Suivi logistique et documentation', 15.90),
('Inspection finale des lots', 21.30),
('Test de conformité aux normes', 22.40),
('Réglage de la température de moulage', 18.60),
('Test de résistance mécanique des pièces', 23.00),
('Contrôle visuel des surfaces', 20.10),
('Polissage final des produits', 21.50),
('Assemblage des kits plastiques', 22.80),
('Étiquetage final des kits', 17.95),
('Conditionnement secondaire', 15.60),
('Stockage intermédiaire', 14.20),
('Préparation des commandes spéciales', 16.40),
('Gestion des retours clients', 18.20),
('Séchage final des pièces', 16.50),
('Préparation des moules pour nouvelle production', 21.90),
('Montage et nettoyage des filières', 22.30),
('Refroidissement post-extrusion', 16.95),
('Découpe finale des pièces extrudées', 18.20),
('Inspection dimensionnelle des produits finis', 21.10),
('Test chimique final', 22.40),
('Contrôle qualité optique final', 19.70),
('Conditionnement final pour livraison', 15.80),
('Étiquetage et scellage des cartons', 14.50),
('Stockage final en entrepôt', 12.95),
('Transport interne vers quai', 13.40),
('Préparation pour transport international', 16.10),
('Chargement des camions et containers', 17.25)
ON CONFLICT (operation) DO NOTHING;